version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gradle/run:
          command: lintKotlin
      - gradle/run:
          command: detekt

workflows:
  build:
    jobs:
      - build
