name: Pull request
on:
  pull_request:
    branches: main
    types: [ synchronize, opened, reopened, ready_for_review ]
jobs:
  pull_request:
    runs-on: macos-latest
    if: github.event.pull_request.draft == false # Do not run anything on a draft PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeBinaries
